name: Test
on: [push, pull_request]
jobs:
image: Ubuntu  # образ для сборки
stack: jdk 11  # версия JDK
branches:
  only:
    - master  # ветка git
build: off  
install:
chmod +x gradlew 

  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
